import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "PrintZone",
  icons: {
    icon: "/logo.png",
  },
  description: "Generated by Boburov Shukurullo for PrintZone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
    </html>
  );
}
